# Site settings
title: Shreya Sajal
# description: |
#   Louis Rassaby is a NYC-based software engineer and entrepreneur currently at Google.
#   He's the founder of Wirefreight, a customer service platform for freight. Previously, Louis led the new products engineering team
#   at Phosphorus Genomics.

url: ssajal.github.io

about_title: About Me
projects_title: Home

# User settings
# user_description_appendix: 
#   [github]: https://github.com/shreyasajal
#   [gh-pages]: https://pages.github.com/
#   [jekyll]: https://jekyllrb.com


email: ssajal@iitg.ac.in
linkedin: shreyasajal
github: shreyasajal
kaggle: shreyasajal

relevant_tags: ['Statistics', 'Machine Learning', 'Deep Learning']

# resume_url: https://docs.google.com/document/d/1dJIboSF-ktdaP28DDu-gcuOW1SCCnkSdqtodJGwYkaA/export?format=pdf
# music_resume_url: https://docs.google.com/document/d/17F3g8jx2UHby77P7shJlsKAW2Efasuc1HuQ3Ro3v3zI/export?format=pdf

author: Shreya Sajal
author_title: Pre-Final Yearite @IIT Guwahati| Kaggle Notebooks Master
author_photo: profile-photo.jpg
user_description_short: |
  I'm a Pre Final Year Student at IIT Guwahati.I am a Kaggle Notebooks Master and will be interning as an Applied Scientist Intern with Amazon in 2022.
  I like to write about the topics I read and the new concepts I stumble upon,and here you can find a collection of my blogs on different topics in statistics,machine learning and deep learning.

## Disqus
disqus_identifier: rassaby

## Tracker
google_analytics_id: UA-109461282-1

keywords: 'software,engineer,design,scala,cello,music,louis rassaby,rassaby'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


plugins:
  - jekyll-feed


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']
